FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-bdc-federated-flwr-node"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_bdc-federated-flwr-node.py /tmp/dags/
COPY files/bdc_federated_flwr_node /tmp/dags/bdc_federated_flwr_node